### ISSUE TITLE
Create separate queries for job list, job, and job ad

### ISSUE THREAD

**Issue by andersloren** [andersloren/headhunter-backend#10]
# Background
Right now, the entire table of jobs are retrieved from the database with one single query to retrieve the ads.

Instead, we will try to use create two queries:

1. Retrieve the titles of the jobs.
2. Retrieve the information on the specific job that was clicked in the job list.

#Tasks
- [x] JobTitlesDtoView;
- [x] Converter?
- [x] Controller Layer: getJobTitles(String email);
- [x] Service Layer: getJobTitles(String email);
- [x] Custom Query in repository layer for only fetching job names and ids.

- [ ] getJobDetails (expand on this task as we get here)

**Comment by andersloren** [comment]
This issue is now done as of #15
